In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [27]:
ctu_13 = pd.read_csv("../Datasets/ctu-13.labeled.cleaned.csv")

In [17]:
ctu_13.head()

src            dst   port proto  \
0  147.32.84.134  147.32.192.34  993.0   tcp   
1  147.32.84.134    147.32.80.9   53.0   udp   
2  147.32.84.134  173.194.16.96   80.0   tcp   
3  147.32.84.134  193.41.230.73   80.0   tcp   
4  147.32.84.134  193.41.230.85  443.0   tcp   

                                               State        label   class  \
0                                      990I0I*z*Z0I0  Normal-Jist  normal   
1  11.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R...  Normal-Jist  normal   
2                                              96.F.  Normal-Jist  normal   
3          66.Z.z.W.W.Z.Z.I.Z.Z.Z.Z.Z+W.F.Z.Z.z.Z.z.  Normal-Jist  normal   
4                                      99.Z.z.Z.I.Z+  Normal-Jist  normal   

   modelsize  
0         13  
1       4879  
2          5  
3         41  
4         13

In [4]:
ctu_13["class"].value_counts()

botnet    6274
normal    2790
Name: class, dtype: int64

In [5]:
ctu_13["label"].value_counts()

Botnet-TCP-Attempt-SPAM                                      4338
Normal-Stribrek                                              1009
Normal-Jist                                                   913
Normal-Grill                                                  768
Botnet-TCP-Established-HTTP-Ad                                487
Botnet-TCP-WEB-Established                                    378
Botnet-UDP-DNS                                                312
Botnet-TCP-WEB-Established-SSL                                210
Botnet-UDP-Attempt-DNS                                         74
Botnet-TCP-CC-HTTP-Not-Encrypted                               71
Normal-UDP-NTP-server                                          67
Botnet-TCP-Established-SSL-Microsoft                           58
Botnet-TCP-HTTP-Google-Net-Established                         50
Botnet-TCP-Established-SPAM                                    49
Botnet-TCP-CC-Plain-HTTP-Encrypted-Data                        38
Botnet-TCP

In [4]:
def change_class(x):
    if x == "botnet":
        return 1
    elif x== "normal":
        return 0

In [5]:
ctu_13["class"] = ctu_13["class"].apply(change_class)

In [7]:
ctu_13["class"].value_counts()

1    6274
0    2790
Name: class, dtype: int64

In [4]:
sum(ctu_13["State"].str.len() > 75)

654

In [21]:
ctu_13.iloc[1977]["State"]

'44.U,U.R.U.U,W.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.R,R.d.U.A.R.d.U.U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,R.U.U.U.R.U.U,U.U,U.U,U.R.W.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,u,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.W,U.U.U.U,U.U,U.R,U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.R,R.D.U.A.R.D.U.U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,W.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.S,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.W.U.U,U.U,U.U,U.R.U.U,W.U,U.U,U.R.U.U,U.U,U.U,W.R.U.U,U.U,U.U,U.R.U.U,Z.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.W,U.R,U.U.U.U,U.R,W.U.U.a.R.D.U.W.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,r.U.U,U.U,U.U,U.R.U.U,U.U,W.U,U.R.U.U,U.U,U.U,U.R.U.U,U.U,U.U,r,W.U.U.U,U.W,U.R,U.U.U.U,U.U,U.R,U.U.U.U,U.U,U.R,U.U.U.

In [19]:
ctu_13.rename(columns={"State":"domain"}, inplace=True)

In [22]:
ctu_13.drop(["src","dst","port","proto","label","modelsize"], axis=1, inplace=True)

In [24]:
ctu_13.to_csv("ctu_13_for_cnn_test.csv", index=False)

Resultados de la CNN (si no se ve bien abrir celda)

[[ 760   69]
 [  83 1781]]
              precision    recall  f1-score   support

      normal     0.9015    0.9168    0.9091       829
      botnet     0.9627    0.9555    0.9591      1864

   micro avg     0.9436    0.9436    0.9436      2693
   macro avg     0.9321    0.9361    0.9341      2693
weighted avg     0.9439    0.9436    0.9437      2693

TN:  760
FP:  69
FN:  83
TP:  1781
False Alarm Rate:  0.08323281061519903
Precision Rate:  0.9627027027027028
Recall Rate:  0.9554721030042919

Con CNN igual a tunnel_model (pero con 256 filtros) y cortando las candenas con 200 caracteres, y a batch=20

Caracteres que usa el sistema de codificacion

In [64]:
len('abcdefghiABCDEFGHIrstuvwxyzRSTUVWXYZ0123456789.,+*')

50

Resultados CNN tunnel( 256 filtros + densa 256, batch=256,epochs=10) cortando en 1000 las cadenas

```
[[ 785   44]
 [ 112 1752]]
              precision    recall  f1-score   support

      normal     0.8751    0.9469    0.9096       829
      botnet     0.9755    0.9399    0.9574      1864

   micro avg     0.9421    0.9421    0.9421      2693
   macro avg     0.9253    0.9434    0.9335      2693
weighted avg     0.9446    0.9421    0.9427      2693

TN:  785
FP:  44
FN:  112
TP:  1752
False Alarm Rate:  0.05307599517490953
Precision Rate:  0.9755011135857461
Recall Rate:  0.9399141630901288
```

Resultados LSTM woodbridge (batch=256, epochs=1) cortando en 1000 las cadenas
```
[[   5  824]
 [   0 1864]]
              precision    recall  f1-score   support

      normal     1.0000    0.0060    0.0120       829
      botnet     0.6935    1.0000    0.8190      1864

   micro avg     0.6940    0.6940    0.6940      2693
   macro avg     0.8467    0.5030    0.4155      2693
weighted avg     0.7878    0.6940    0.5706      2693

TN:  5
FP:  824
FN:  0
TP:  1864
False Alarm Rate:  0.9939686369119421
Precision Rate:  0.6934523809523809
Recall Rate:  1.0
```

Resultados LSTM woodbridge + densa 256 (batch=256, epochs=1) cortando en 1000 las cadenas

```
[[   0  829]
 [   0 1864]]

              precision    recall  f1-score   support

      normal     0.0000    0.0000    0.0000       829
      botnet     0.6922    1.0000    0.8181      1864

   micro avg     0.6922    0.6922    0.6922      2693
   macro avg     0.3461    0.5000    0.4090      2693
weighted avg     0.4791    0.6922    0.5662      2693

TN:  0
FP:  829
FN:  0
TP:  1864
False Alarm Rate:  1.0
Precision Rate:  0.6921648718900854
Recall Rate:  1.0
```

Resultados LSTM woodbridge (batch=256, epochs=10) cortando en 75 las cadenas
```
[[ 811   18]
 [ 371 1493]]
              precision    recall  f1-score   support

      normal     0.6861    0.9783    0.8066       829
      botnet     0.9881    0.8010    0.8847      1864

   micro avg     0.8556    0.8556    0.8556      2693
   macro avg     0.8371    0.8896    0.8457      2693
weighted avg     0.8951    0.8556    0.8607      2693

TN:  811
FP:  18
FN:  371
TP:  1493
False Alarm Rate:  0.021712907117008445
Precision Rate:  0.9880873593646592
Recall Rate:  0.8009656652360515
```

Resultados LSTM woodbridge (batch=256, epochs=20) cortando en 75 las cadenas
```
[[ 671  158]
 [  91 1773]]
              precision    recall  f1-score   support

      normal     0.8806    0.8094    0.8435       829
      botnet     0.9182    0.9512    0.9344      1864

   micro avg     0.9075    0.9075    0.9075      2693
   macro avg     0.8994    0.8803    0.8889      2693
weighted avg     0.9066    0.9075    0.9064      2693

TN:  671
FP:  158
FN:  91
TP:  1773
False Alarm Rate:  0.19059107358262967
Precision Rate:  0.9181771103055412
Recall Rate:  0.9511802575107297

```

Resultados LSTM woodbridge + densa 512 (batch=256, epochs=30) cortando en 75 las cadenas
```
[[ 771   58]
 [ 147 1717]]
              precision    recall  f1-score   support

      normal     0.8399    0.9300    0.8827       829
      botnet     0.9673    0.9211    0.9437      1864

   micro avg     0.9239    0.9239    0.9239      2693
   macro avg     0.9036    0.9256    0.9132      2693
weighted avg     0.9281    0.9239    0.9249      2693

TN:  771
FP:  58
FN:  147
TP:  1717
False Alarm Rate:  0.06996381182147166
Precision Rate:  0.9673239436619718
Recall Rate:  0.921137339055794

```

Misma estructura que anterior pero cortando en 1000 las cadenas
```
[[  19  810]
 [   0 1864]]
              precision    recall  f1-score   support

      normal     1.0000    0.0229    0.0448       829
      botnet     0.6971    1.0000    0.8215      1864

   micro avg     0.6992    0.6992    0.6992      2693
   macro avg     0.8485    0.5115    0.4332      2693
weighted avg     0.7903    0.6992    0.5824      2693

TN:  19
FP:  810
FN:  0
TP:  1864
False Alarm Rate:  0.97708082026538
Precision Rate:  0.6970830216903515
Recall Rate:  1.0
```

Misma estructura que anterior, cortando a los 1000 pero con Masking
```
[[ 745   84]
 [  86 1778]]
              precision    recall  f1-score   support

      normal     0.8965    0.8987    0.8976       829
      botnet     0.9549    0.9539    0.9544      1864

   micro avg     0.9369    0.9369    0.9369      2693
   macro avg     0.9257    0.9263    0.9260      2693
weighted avg     0.9369    0.9369    0.9369      2693

TN:  745
FP:  84
FN:  86
TP:  1778
False Alarm Rate:  0.10132689987937274
Precision Rate:  0.9548872180451128
Recall Rate:  0.953862660944206

```

Random Forest, feature vector, cadenas completas
```
[[ 713   99]
 [ 109 1799]]

              precision    recall  f1-score   support

           0       0.87      0.88      0.87       812
           1       0.95      0.94      0.95      1908

    accuracy                           0.92      2720
   macro avg       0.91      0.91      0.91      2720
weighted avg       0.92      0.92      0.92      2720

```

Random Forest, feature vector, cadenas sin los primeros 5 caracteres
```
[[ 609  121]
 [  85 1201]]

              precision    recall  f1-score   support

           0       0.88      0.83      0.86       730
           1       0.91      0.93      0.92      1286

    accuracy                           0.90      2016
   macro avg       0.89      0.88      0.89      2016
weighted avg       0.90      0.90      0.90      2016


```

In [17]:
ctu_13_short = ctu_13[ctu_13["State"].str.len()<100].copy()

In [18]:
ctu_13_short.rename(columns={"State":"domain"}, inplace=True)

In [19]:
ctu_13_short.drop(["src","dst","port","proto","label","modelsize"], axis=1, inplace=True)

In [21]:
ctu_13.to_csv("ctu_13_short_for_test.csv", index=False)

In [7]:
ctu_13_harpo = pd.read_csv("../Datasets/ctu13subs.csv")

In [15]:
ctu_13_harpo.head(10)

State        class
0  990I0I*z*Z0  Normal-Jist
1  .R.r.r.r.r.  Normal-Jist
2        96.F.  Normal-Jist
3  W.F.Z.Z.z.Z  Normal-Jist
4  .Z.z.Z.I.Z+  Normal-Jist
5  66.w.X.W*W.  Normal-Jist
6      67.W*X.  Normal-Jist
7  W.X.X.X*X.X  Normal-Jist
8    76*W.w.X.  Normal-Jist
9  Z.Z.Z.Z.W.W  Normal-Jist

In [14]:
ctu_13[ctu_13["State"] == ""]

src              dst    port proto State  \
2     147.32.84.134    173.194.16.96    80.0   tcp         
13    147.32.84.134     194.79.54.24    80.0   tcp         
19    147.32.84.134      199.7.52.72    80.0   tcp         
30    147.32.84.134    62.168.44.115    80.0   tcp         
33    147.32.84.134       64.4.44.94  1863.0   tcp         
40    147.32.84.134    69.171.242.40    80.0   tcp         
46    147.32.84.134   74.125.232.193    80.0   tcp         
54    147.32.84.134   74.125.232.201   443.0   tcp         
59    147.32.84.134   74.125.232.207    80.0   tcp         
63    147.32.84.134    77.104.226.22    80.0   tcp         
65    147.32.84.134    80.239.149.10    80.0   tcp         
74    147.32.84.134    82.208.47.218    80.0   tcp         
115   147.32.84.164    195.24.233.18    80.0   tcp         
122   147.32.84.164      2.21.108.20    80.0   tcp         
169   147.32.84.164   74.125.232.207   443.0   tcp         
174   147.32.84.164   74.125.232.221   443.0   tcp         
177   147.32.84.164   74.125.235.159    80.0   tcp         
178   147.32.84.164    74.125.237.31    80.0   tcp         
189   147.32.84.164      77.75.76.69    80.0   tcp         
198   147.32.84.164      77.78.99.25    80.0   tcp         
210   147.32.84.164   91.198.174.234    80.0   tcp         
215   147.32.84.164    95.168.214.66    80.0   tcp         
217   147.32.84.165  109.200.239.148  6667.0   tcp         
218   147.32.84.165    109.235.49.72    53.0   udp         
230   147.32.84.165   115.240.199.38  6667.0   tcp         
231   147.32.84.165   115.98.214.212  6667.0   tcp         
237   147.32.84.165   117.204.64.132  6667.0   tcp         
240   147.32.84.165    117.207.5.248  6667.0   tcp         
241   147.32.84.165     117.207.7.56  6667.0   tcp         
243   147.32.84.165     117.242.61.2  6667.0   tcp         
...             ...              ...     ...   ...   ...   
8918  147.32.84.165   77.127.115.133  6667.0   tcp         
8925  147.32.84.165      78.58.99.95  6667.0   tcp         
8926  147.32.84.165   79.113.190.202  6667.0   tcp         
8928  147.32.84.165    80.191.187.36  6667.0   tcp         
8929  147.32.84.165   80.191.196.145  6667.0   tcp         
8930  147.32.84.165    80.72.108.202  6667.0   tcp         
8933  147.32.84.165    82.230.33.111  6667.0   tcp         
8934  147.32.84.165   82.232.103.247  6667.0   tcp         
8936  147.32.84.165      82.99.253.2  6667.0   tcp         
8938  147.32.84.165    83.148.82.159  6667.0   tcp         
8940  147.32.84.165    84.247.61.206  6667.0   tcp         
8942  147.32.84.165   85.186.104.184  6667.0   tcp         
8944  147.32.84.165     86.123.31.54  6667.0   tcp         
8950  147.32.84.165    91.203.175.83  6667.0   tcp         
8952  147.32.84.165     91.90.126.12  6667.0   tcp         
8953  147.32.84.165     93.17.128.25    25.0   tcp         
8955  147.32.84.165    93.180.230.38  6667.0   tcp         
8958  147.32.84.165    94.245.116.13    80.0   tcp         
8961  147.32.84.165    94.63.149.152    80.0   tcp         
8964  147.32.84.165     94.95.56.138  6667.0   tcp         
8970  147.32.84.165     98.136.59.15    25.0   tcp         
8977  147.32.84.165   98.139.214.154    25.0   tcp         
8979  147.32.84.165    98.154.67.160  6667.0   tcp         
8984  147.32.84.170      199.7.51.72    80.0   tcp         
9009  147.32.84.170     64.12.73.165   443.0   tcp         
9016  147.32.84.170   74.125.232.196   443.0   tcp         
9018  147.32.84.170   74.125.232.197   443.0   tcp         
9024  147.32.84.170   74.125.232.201   443.0   tcp         
9034  147.32.84.170   74.125.232.206   443.0   tcp         
9053  147.32.84.170     91.189.89.76   443.0   tcp         

                                            label   class  modelsize  
2                                     Normal-Jist  normal          5  
13                                    Normal-Jist  normal          5  
19                                    Normal-Jist  normal          5  
30         

In [28]:
ctu_13["State"] = ctu_13["State"].apply(lambda x: x[5:10])

In [31]:
import string

def get_valid_characters():
    """
        Returns a string with all the valid characters
    :return:
    """
    # '$' acts as the masking character
    return 'abcdefghiABCDEFGHIrstuvwxyzRSTUVWXYZ0123456789.,+*'

def mapping():
    chars = get_valid_characters()
    charmap = {}
    for i, c in enumerate(chars):
        charmap[c] = i
    return charmap

def tokenize(data, maxlen=45):
    charmap = mapping()
    x_data = [[charmap[c] for c in list(x)] for x in data]
    return x_data

#string.ascii_lowercase + string.digits + '-_.'
x = tokenize(ctu_13.iloc[:3]['State'].values, 10)

In [32]:
x

[[17, 49, 26, 49, 35], [27, 46, 27, 46, 27], []]