In [1]:
import pandas as pd
import numpy as np

### Experiment random pos for LSTM with different maxlen

In [4]:
sizes_string = [10, 25, 75]
test = "ctu19_to_test.csv"
for maxlen in sizes_string:
    train = "./Random_pos/ctu13subs" + str(maxlen) + "_net.csv"
    results = "results_LSTM_random_pos_size_" + str(maxlen) + ".csv"
    for i in range(0,10):
        !python3 train_data_preparation.py --csv $train --maxlen $maxlen
        !python3 dga_classifier.py --save-model endgame.h5 --maxlen $maxlen
        !python3 train_data_preparation.py --csv $test --test-only --maxlen $maxlen
        !python3 dga_classifier.py --test-only -m endgame.h5 -r $results --maxlen $maxlen
        print("##--------------------------------------------------------------------##")

Using TensorFlow backend.
Using TensorFlow backend.
(7251, 75) (7251,)
(18, 75) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-18 18:34:11.770050: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-18 18:34:12.036194: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-18 18:34:12.036562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-18 18:34:12.036576: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-18 18:34:12.296631: I te

dense_1 (Dense)              (None, 1)                 129       
Total params: 138,241
Trainable params: 138,241
Non-trainable params: 0
_________________________________________________________________
None
[[  758   842]
 [14277 11668]]
              precision    recall  f1-score   support

      normal     0.0504    0.4738    0.0911      1600
      botnet     0.9327    0.4497    0.6068     25945

   micro avg     0.4511    0.4511    0.4511     27545
   macro avg     0.4916    0.4617    0.3490     27545
weighted avg     0.8814    0.4511    0.5769     27545

TN:  758
FP:  842
FN:  14277
TP:  11668
False Alarm Rate:  0.52625
Precision Rate:  0.9326938449240607
Recall Rate:  0.44972056272884947
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 75) (7251,)
(18, 75) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-18 18:35:26.

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 75, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
Total params: 138,241
Trainable params: 138,241
Non-trainable params: 0
_________________________________________________________________
None
[[  656   944]
 [14937 11008]]
              precision    recall  f1-score   support

      normal     0.0421    0.4100    0.0763      1600
      botnet     0.9210    0.4243    0.5809     25945

   micro avg     0.4235    0.4235    0.4235     27545
   macro avg  

2020-04-18 18:37:49.032630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-18 18:37:49.032657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-18 18:37:49.032680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-18 18:37:49.032992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 75, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_____________________________________________________

Using TensorFlow backend.
Using TensorFlow backend.
2020-04-18 18:39:02.896908: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-18 18:39:03.181127: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-18 18:39:03.181497: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-18 18:39:03.181512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-18 18:39:03.443619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-18 18:39:03.443648: I tenso

7251/7251 [==============================] - 2s 279us/step - loss: 0.1613 - acc: 0.9304 - val_loss: 0.0642 - val_acc: 1.0000
Epoch 23/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1578 - acc: 0.9316 - val_loss: 0.0538 - val_acc: 1.0000
Epoch 24/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1574 - acc: 0.9316 - val_loss: 0.0575 - val_acc: 1.0000
Epoch 25/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1556 - acc: 0.9331 - val_loss: 0.0565 - val_acc: 1.0000
Epoch 26/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1538 - acc: 0.9330 - val_loss: 0.0589 - val_acc: 1.0000
Epoch 27/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1544 - acc: 0.9319 - val_loss: 0.0552 - val_acc: 1.0000
Epoch 28/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1539 - acc: 0.9326 - val_loss: 0.0566 - val_acc: 1.0000
Epoch 29/30
7251/7251 [==============================

7251/7251 [==============================] - 2s 278us/step - loss: 0.1746 - acc: 0.9248 - val_loss: 0.2379 - val_acc: 0.8889
Epoch 17/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1733 - acc: 0.9254 - val_loss: 0.2218 - val_acc: 0.8889
Epoch 18/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1680 - acc: 0.9269 - val_loss: 0.2332 - val_acc: 0.8889
Epoch 19/30
7251/7251 [==============================] - 2s 277us/step - loss: 0.1710 - acc: 0.9255 - val_loss: 0.2264 - val_acc: 0.8889
Epoch 20/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1700 - acc: 0.9270 - val_loss: 0.2235 - val_acc: 0.8889
Epoch 21/30
7251/7251 [==============================] - 2s 277us/step - loss: 0.1665 - acc: 0.9279 - val_loss: 0.2201 - val_acc: 0.8889
Epoch 22/30
7251/7251 [==============================] - 2s 277us/step - loss: 0.1664 - acc: 0.9284 - val_loss: 0.1970 - val_acc: 0.8889
Epoch 23/30
7251/7251 [==============================

7251/7251 [==============================] - 2s 278us/step - loss: 0.1765 - acc: 0.9269 - val_loss: 0.1629 - val_acc: 0.9444
Epoch 11/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1773 - acc: 0.9248 - val_loss: 0.1558 - val_acc: 0.9444
Epoch 12/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1732 - acc: 0.9283 - val_loss: 0.1629 - val_acc: 0.9444
Epoch 13/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1765 - acc: 0.9280 - val_loss: 0.1366 - val_acc: 0.9444
Epoch 14/30
7251/7251 [==============================] - 2s 277us/step - loss: 0.1717 - acc: 0.9284 - val_loss: 0.1758 - val_acc: 0.9444
Epoch 15/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1715 - acc: 0.9283 - val_loss: 0.1533 - val_acc: 0.9444
Epoch 16/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1700 - acc: 0.9281 - val_loss: 0.1245 - val_acc: 0.9444
Epoch 17/30
7251/7251 [==============================

7251/7251 [==============================] - 3s 479us/step - loss: 0.4059 - acc: 0.8744 - val_loss: 0.5892 - val_acc: 0.8333
Epoch 2/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.2529 - acc: 0.9084 - val_loss: 0.5231 - val_acc: 0.8333
Epoch 3/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.2161 - acc: 0.9105 - val_loss: 0.4509 - val_acc: 0.8333
Epoch 4/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.2036 - acc: 0.9173 - val_loss: 0.3855 - val_acc: 0.9444
Epoch 5/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1934 - acc: 0.9215 - val_loss: 0.3811 - val_acc: 0.9444
Epoch 6/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1870 - acc: 0.9250 - val_loss: 0.2958 - val_acc: 0.9444
Epoch 7/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1870 - acc: 0.9228 - val_loss: 0.3158 - val_acc: 0.9444
Epoch 8/30
7251/7251 [==============================] - 2s 

2020-04-18 18:45:22.083671: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-18 18:45:22.084072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-18 18:45:22.084086: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-18 18:45:22.341864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-18 18:45:22.341907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-18 18:45:22.341913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-18 18:45:22.342194: I tensorflow/core/common_runtime/gpu/gpu_device.c

TN:  898
FP:  702
FN:  15207
TP:  10738
False Alarm Rate:  0.43875
Precision Rate:  0.9386363636363636
Recall Rate:  0.41387550587781846
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f49d8fbca90>>
Traceback (most recent call last):
  File "/home/fpalau/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 712, in __del__
TypeError: 'NoneType' object is not callable
##--------------------------------------------------------------------##


### Experiment LSTM different maxlen from beginning

In [ ]:
sizes_string = [10, 25]#, 75, 100, 500, 1000]
test = "ctu19_to_test.csv"
train = "ctu_13_for_LSTM.csv"
for maxlen in sizes_string:
    results = "results_LSTM_size_" + str(maxlen) + ".csv"
    for i in range(0,10):
        !python3 train_data_preparation.py --csv $train --maxlen $maxlen
        !python3 dga_classifier.py --save-model endgame.h5 --maxlen $maxlen
        !python3 train_data_preparation.py --csv $test --test-only --maxlen $maxlen
        !python3 dga_classifier.py --test-only -m endgame.h5 -r $results --maxlen $maxlen
        print("##--------------------------------------------------------------------##")

Using TensorFlow backend.
  File "dga_classifier.py", line 54
    print(test_x_data.shape, test_y_data.shape)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
Using TensorFlow backend.
  File "dga_classifier.py", line 54
    print(test_x_data.shape, test_y_data.shape)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
##--------------------------------------------------------------------##
Using TensorFlow backend.
  File "dga_classifier.py", line 54
    print(test_x_data.shape, test_y_data.shape)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
Using TensorFlow backend.
  File "dga_classifier.py", line 54
    print(test_x_data.shape, test_y_data.shape)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
##-------------------------------------------------

7251/7251 [==============================] - 0s 43us/step - loss: 0.2643 - acc: 0.8930 - val_loss: 0.3057 - val_acc: 0.8889
Epoch 3/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.2358 - acc: 0.8984 - val_loss: 0.2775 - val_acc: 0.8889
Epoch 4/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.2266 - acc: 0.9024 - val_loss: 0.2570 - val_acc: 0.9444
Epoch 5/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.2204 - acc: 0.9053 - val_loss: 0.2518 - val_acc: 0.9444
Epoch 6/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.2132 - acc: 0.9061 - val_loss: 0.2572 - val_acc: 0.9444
Epoch 7/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.2089 - acc: 0.9061 - val_loss: 0.2644 - val_acc: 0.8889
Epoch 8/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.2060 - acc: 0.9084 - val_loss: 0.2751 - val_acc: 0.8889
Epoch 9/30
7251/7251 [==============================] - 0s 43us/st

Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 13:52:46.898940: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:52:47.159841: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 13:52:47.160234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 13:52:47.160249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 13:52:47.419617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 13:52:47.419647: I 

[[  800   800]
 [13804 12141]]
              precision    recall  f1-score   support

      normal     0.0548    0.5000    0.0987      1600
      botnet     0.9382    0.4680    0.6244     25945

   micro avg     0.4698    0.4698    0.4698     27545
   macro avg     0.4965    0.4840    0.3616     27545
weighted avg     0.8869    0.4698    0.5939     27545

TN:  800
FP:  800
FN:  13804
TP:  12141
False Alarm Rate:  0.5
Precision Rate:  0.9381809751951163
Recall Rate:  0.46795143572942766
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 10) (7251,)
(18, 10) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 13:53:08.734790: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:53:09.000923: I tensorflow/stream_executor/cu

[[  768   832]
 [13924 12021]]
              precision    recall  f1-score   support

      normal     0.0523    0.4800    0.0943      1600
      botnet     0.9353    0.4633    0.6197     25945

   micro avg     0.4643    0.4643    0.4643     27545
   macro avg     0.4938    0.4717    0.3570     27545
weighted avg     0.8840    0.4643    0.5892     27545

TN:  768
FP:  832
FN:  13924
TP:  12021
False Alarm Rate:  0.52
Precision Rate:  0.9352680308099276
Recall Rate:  0.4633262671034881
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 25) (7251,)
(18, 25) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 13:53:30.662829: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:53:30.923150: I tensorflow/stream_executor/cu

[[  796   804]
 [13924 12021]]
              precision    recall  f1-score   support

      normal     0.0541    0.4975    0.0975      1600
      botnet     0.9373    0.4633    0.6201     25945

   micro avg     0.4653    0.4653    0.4653     27545
   macro avg     0.4957    0.4804    0.3588     27545
weighted avg     0.8860    0.4653    0.5898     27545

TN:  796
FP:  804
FN:  13924
TP:  12021
False Alarm Rate:  0.5025
Precision Rate:  0.9373099415204679
Recall Rate:  0.4633262671034881
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fd87fd3bf28>>
Traceback (most recent call last):
  File "/home/fpalau/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 712, in __del__
  File "/home/fpalau/.local/lib/python3.5/site-packages/tensorflow/python/framework/c_api_util.py", line 31, in __init__
TypeError: 'NoneType' object is not callable
##-------------------------------------------------------------

2020-04-19 13:54:31.443963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 13:54:31.443993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-19 13:54:31.444016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-19 13:54:31.444315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_____________________________________________________

Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 13:55:03.920176: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:55:04.182958: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 13:55:04.183353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 13:55:04.183367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 13:55:04.440985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 13:55:04.441028: I tenso

7251/7251 [==============================] - 1s 94us/step - loss: 0.1547 - acc: 0.9379 - val_loss: 0.2101 - val_acc: 0.8889
Epoch 29/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1537 - acc: 0.9349 - val_loss: 0.2215 - val_acc: 0.8889
Epoch 30/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1516 - acc: 0.9335 - val_loss: 0.2186 - val_acc: 0.8889
[[ 493   59]
 [  61 1182]]
              precision    recall  f1-score   support

      normal     0.8899    0.8931    0.8915       552
      botnet     0.9525    0.9509    0.9517      1243

   micro avg     0.9331    0.9331    0.9331      1795
   macro avg     0.9212    0.9220    0.9216      1795
weighted avg     0.9332    0.9331    0.9332      1795

TN:  493
FP:  59
FN:  61
TP:  1182
False Alarm Rate:  0.1068840579710145
Precision Rate:  0.9524576954069299
Recall Rate:  0.9509251810136766
Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 13:55:37.246096: I tensorflow/core/platform/c

Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 13:56:00.611097: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:56:00.887411: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 13:56:00.887809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 13:56:00.887823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 13:56:01.151940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 13:56:01.151982: I tenso

7251/7251 [==============================] - 1s 94us/step - loss: 0.1560 - acc: 0.9331 - val_loss: 0.3118 - val_acc: 0.7778
Epoch 29/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1513 - acc: 0.9344 - val_loss: 0.3067 - val_acc: 0.7778
Epoch 30/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1515 - acc: 0.9342 - val_loss: 0.2817 - val_acc: 0.7778
[[ 510   42]
 [  65 1178]]
              precision    recall  f1-score   support

      normal     0.8870    0.9239    0.9051       552
      botnet     0.9656    0.9477    0.9566      1243

   micro avg     0.9404    0.9404    0.9404      1795
   macro avg     0.9263    0.9358    0.9308      1795
weighted avg     0.9414    0.9404    0.9407      1795

TN:  510
FP:  42
FN:  65
TP:  1178
False Alarm Rate:  0.07608695652173914
Precision Rate:  0.9655737704918033
Recall Rate:  0.9477071600965407
Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 13:56:33.613195: I tensorflow/core/platform/

7251/7251 [==============================] - 1s 93us/step - loss: 0.1576 - acc: 0.9327 - val_loss: 0.0956 - val_acc: 1.0000
Epoch 23/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1545 - acc: 0.9331 - val_loss: 0.0900 - val_acc: 1.0000
Epoch 24/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1547 - acc: 0.9335 - val_loss: 0.1023 - val_acc: 1.0000
Epoch 25/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1535 - acc: 0.9361 - val_loss: 0.0904 - val_acc: 1.0000
Epoch 26/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1503 - acc: 0.9363 - val_loss: 0.0852 - val_acc: 1.0000
Epoch 27/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1485 - acc: 0.9359 - val_loss: 0.0835 - val_acc: 1.0000
Epoch 28/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1478 - acc: 0.9364 - val_loss: 0.0910 - val_acc: 1.0000
Epoch 29/30
7251/7251 [==============================] - 1s 