In [1]:
import pandas as pd
import numpy as np

### Experiment random pos for LSTM with different maxlen

In [1]:
sizes_string = [10, 25, 75]

for maxlen in sizes_string:
    train = "./Random_pos/ctu13subs" + str(maxlen) + "_net.csv"
    test = "ctu19_for_LSTM_random_pos_size_" + str(maxlen) + ".csv"
    results = "results_LSTM_random_pos_size_" + str(maxlen) + ".csv"
    for i in range(0,10):
        !python3 train_data_preparation.py --csv $train --maxlen $maxlen
        !python3 dga_classifier.py --save-model endgame.h5 --maxlen $maxlen
        !python3 train_data_preparation.py --csv $test --test-only --maxlen $maxlen
        !python3 dga_classifier.py --test-only -m endgame.h5 -r $results --maxlen $maxlen
        print("##--------------------------------------------------------------------##")

Using TensorFlow backend.
Using TensorFlow backend.
(7251, 10) (7251,)
(18, 10) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 17:12:24.288283: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 17:12:24.558308: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 17:12:24.558802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 17:12:24.558817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 17:12:24.849505: I te

[[  875   725]
 [16172  9773]]
              precision    recall  f1-score   support

      normal     0.0513    0.5469    0.0938      1600
      botnet     0.9309    0.3767    0.5363     25945

   micro avg     0.3866    0.3866    0.3866     27545
   macro avg     0.4911    0.4618    0.3151     27545
weighted avg     0.8798    0.3866    0.5106     27545

TN:  875
FP:  725
FN:  16172
TP:  9773
False Alarm Rate:  0.453125
Precision Rate:  0.930939226519337
Recall Rate:  0.3766814415108884
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f976b777be0>>
Traceback (most recent call last):
  File "/home/fpalau/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 712, in __del__
TypeError: 'NoneType' object is not callable
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 10) (7251,)
(18, 10) (18,)
Model lstm_model_endgame 

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 10, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
Total params: 138,241
Trainable params: 138,241
Non-trainable params: 0
_________________________________________________________________
None
[[  869   731]
 [16671  9274]]
              precision    recall  f1-score   support

      normal     0.0495    0.5431    0.0908      1600
      botnet     0.9269    0.3574    0.5159     25945

   micro avg     0.3682    0.3682    0.3682     27545
   macro avg  

2020-04-19 17:13:19.110455: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:13:19.110500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-19 17:13:19.110506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-19 17:13:19.110801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 10, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_____________________________________________________

Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 17:13:38.665224: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 17:13:38.916712: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 17:13:38.917108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 17:13:38.917122: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 17:13:39.177801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:13:39.177831: I tenso

7251/7251 [==============================] - 0s 43us/step - loss: 0.1654 - acc: 0.9288 - val_loss: 0.1427 - val_acc: 0.9444
Epoch 29/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1645 - acc: 0.9286 - val_loss: 0.1438 - val_acc: 0.9444
Epoch 30/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1636 - acc: 0.9308 - val_loss: 0.1443 - val_acc: 0.9444
[[ 469   83]
 [  55 1188]]
              precision    recall  f1-score   support

      normal     0.8950    0.8496    0.8717       552
      botnet     0.9347    0.9558    0.9451      1243

   micro avg     0.9231    0.9231    0.9231      1795
   macro avg     0.9149    0.9027    0.9084      1795
weighted avg     0.9225    0.9231    0.9225      1795

TN:  469
FP:  83
FN:  55
TP:  1188
False Alarm Rate:  0.1503623188405797
Precision Rate:  0.9346970889063729
Recall Rate:  0.9557522123893806
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object 

7251/7251 [==============================] - 0s 43us/step - loss: 0.1722 - acc: 0.9247 - val_loss: 0.3009 - val_acc: 0.8889
Epoch 20/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1722 - acc: 0.9281 - val_loss: 0.2939 - val_acc: 0.8889
Epoch 21/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.1700 - acc: 0.9261 - val_loss: 0.2890 - val_acc: 0.8889
Epoch 22/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.1694 - acc: 0.9284 - val_loss: 0.2864 - val_acc: 0.8889
Epoch 23/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1661 - acc: 0.9304 - val_loss: 0.2869 - val_acc: 0.8889
Epoch 24/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1663 - acc: 0.9299 - val_loss: 0.2859 - val_acc: 0.8889
Epoch 25/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.1664 - acc: 0.9287 - val_loss: 0.2769 - val_acc: 0.8333
Epoch 26/30
7251/7251 [==============================] - 0s 

7251/7251 [==============================] - 0s 43us/step - loss: 0.1891 - acc: 0.9175 - val_loss: 0.1769 - val_acc: 0.8889
Epoch 14/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1860 - acc: 0.9186 - val_loss: 0.1786 - val_acc: 0.8889
Epoch 15/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1840 - acc: 0.9207 - val_loss: 0.1700 - val_acc: 0.8889
Epoch 16/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1826 - acc: 0.9210 - val_loss: 0.1724 - val_acc: 0.8889
Epoch 17/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1799 - acc: 0.9224 - val_loss: 0.1603 - val_acc: 0.8889
Epoch 18/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1795 - acc: 0.9230 - val_loss: 0.1507 - val_acc: 0.8889
Epoch 19/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1773 - acc: 0.9236 - val_loss: 0.1341 - val_acc: 1.0000
Epoch 20/30
7251/7251 [==============================] - 0s 

7251/7251 [==============================] - 0s 44us/step - loss: 0.1981 - acc: 0.9139 - val_loss: 0.2682 - val_acc: 0.8889
Epoch 8/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.1965 - acc: 0.9130 - val_loss: 0.2670 - val_acc: 0.8889
Epoch 9/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1945 - acc: 0.9159 - val_loss: 0.2662 - val_acc: 0.8889
Epoch 10/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.1921 - acc: 0.9160 - val_loss: 0.2652 - val_acc: 0.8889
Epoch 11/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1887 - acc: 0.9184 - val_loss: 0.2784 - val_acc: 0.8889
Epoch 12/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1878 - acc: 0.9179 - val_loss: 0.2879 - val_acc: 0.8889
Epoch 13/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.1857 - acc: 0.9195 - val_loss: 0.2780 - val_acc: 0.8889
Epoch 14/30
7251/7251 [==============================] - 0s 43

7251/7251 [==============================] - 2s 253us/step - loss: 0.3929 - acc: 0.8682 - val_loss: 0.2408 - val_acc: 0.8889
Epoch 2/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.2472 - acc: 0.8996 - val_loss: 0.1644 - val_acc: 0.8889
Epoch 3/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.2218 - acc: 0.9073 - val_loss: 0.1250 - val_acc: 0.8889
Epoch 4/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.2104 - acc: 0.9091 - val_loss: 0.1057 - val_acc: 0.9444
Epoch 5/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.2060 - acc: 0.9120 - val_loss: 0.0919 - val_acc: 0.9444
Epoch 6/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.2016 - acc: 0.9141 - val_loss: 0.0838 - val_acc: 0.9444
Epoch 7/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.1985 - acc: 0.9170 - val_loss: 0.0821 - val_acc: 1.0000
Epoch 8/30
7251/7251 [==============================] - 0s 44us/s

2020-04-19 17:15:24.658855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:15:24.658900: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-19 17:15:24.658905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-19 17:15:24.659204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
7251/7251 [==============================] - 2s 247us/step - loss: 0.4084 - acc: 0.8559 - val_loss: 0.2960 - val_acc: 0.8889
Epoch 2/30
7251/7251 [==============================] - 0s 44us/step - loss: 0.2492 - acc: 0.8988 - val_loss: 0.2734 - val_acc: 0.8333
Epoch 3/30
7251/7251 [==============================] - 0s 43us/step - loss: 0.2229 - acc: 0.9075 - val_loss: 0.2604 - val_

TN:  845
FP:  755
FN:  16157
TP:  9788
False Alarm Rate:  0.471875
Precision Rate:  0.92838850422081
Recall Rate:  0.37725958758913086
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 25) (7251,)
(18, 25) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 17:15:44.163849: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 17:15:44.426621: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 17:15:44.427016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBu

[[  779   821]
 [15713 10232]]
              precision    recall  f1-score   support

      normal     0.0472    0.4869    0.0861      1600
      botnet     0.9257    0.3944    0.5531     25945

   micro avg     0.3997    0.3997    0.3997     27545
   macro avg     0.4865    0.4406    0.3196     27545
weighted avg     0.8747    0.3997    0.5260     27545

TN:  779
FP:  821
FN:  15713
TP:  10232
False Alarm Rate:  0.513125
Precision Rate:  0.925721523568262
Recall Rate:  0.39437271150510694
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 25) (7251,)
(18, 25) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 17:16:15.295299: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 17:16:15.549936: I tensorflow/stream_executo

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
Total params: 138,241
Trainable params: 138,241
Non-trainable params: 0
_________________________________________________________________
None
[[  841   759]
 [16810  9135]]
              precision    recall  f1-score   support

      normal     0.0476    0.5256    0.0874      1600
      botnet     0.9233    0.3521    0.5098     25945

   micro avg     0.3622    0.3622    0.3622     27545
   macro avg  

2020-04-19 17:17:12.783668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:17:12.783712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-19 17:17:12.783718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-19 17:17:12.784002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_____________________________________________________

Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 17:17:43.543481: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 17:17:43.816528: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 17:17:43.816908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 17:17:43.816921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 17:17:44.076317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:17:44.076363: I tenso

7251/7251 [==============================] - 1s 93us/step - loss: 0.1484 - acc: 0.9356 - val_loss: 0.0702 - val_acc: 0.9444
Epoch 29/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1459 - acc: 0.9337 - val_loss: 0.0671 - val_acc: 0.9444
Epoch 30/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1454 - acc: 0.9371 - val_loss: 0.0631 - val_acc: 0.9444
[[ 467   85]
 [  42 1201]]
              precision    recall  f1-score   support

      normal     0.9175    0.8460    0.8803       552
      botnet     0.9339    0.9662    0.9498      1243

   micro avg     0.9292    0.9292    0.9292      1795
   macro avg     0.9257    0.9061    0.9150      1795
weighted avg     0.9289    0.9292    0.9284      1795

TN:  467
FP:  85
FN:  42
TP:  1201
False Alarm Rate:  0.1539855072463768
Precision Rate:  0.9339035769828927
Recall Rate:  0.9662107803700724
Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 17:18:14.648694: I tensorflow/core/platform/c

7251/7251 [==============================] - 1s 94us/step - loss: 0.1596 - acc: 0.9287 - val_loss: 0.1643 - val_acc: 0.9444
Epoch 23/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1564 - acc: 0.9283 - val_loss: 0.1680 - val_acc: 0.9444
Epoch 24/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1581 - acc: 0.9287 - val_loss: 0.1700 - val_acc: 0.9444
Epoch 25/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1561 - acc: 0.9280 - val_loss: 0.1652 - val_acc: 0.9444
Epoch 26/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1511 - acc: 0.9319 - val_loss: 0.1732 - val_acc: 0.9444
Epoch 27/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1511 - acc: 0.9313 - val_loss: 0.1746 - val_acc: 0.9444
Epoch 28/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1487 - acc: 0.9323 - val_loss: 0.1699 - val_acc: 0.9444
Epoch 29/30
7251/7251 [==============================] - 1s 

7251/7251 [==============================] - 1s 93us/step - loss: 0.1721 - acc: 0.9258 - val_loss: 0.1447 - val_acc: 0.9444
Epoch 17/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1704 - acc: 0.9273 - val_loss: 0.1362 - val_acc: 0.9444
Epoch 18/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1681 - acc: 0.9262 - val_loss: 0.1399 - val_acc: 0.9444
Epoch 19/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1667 - acc: 0.9280 - val_loss: 0.1394 - val_acc: 0.9444
Epoch 20/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1649 - acc: 0.9287 - val_loss: 0.1431 - val_acc: 0.8889
Epoch 21/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1642 - acc: 0.9290 - val_loss: 0.1434 - val_acc: 0.8889
Epoch 22/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1622 - acc: 0.9316 - val_loss: 0.1358 - val_acc: 0.9444
Epoch 23/30
7251/7251 [==============================] - 1s 

7251/7251 [==============================] - 1s 94us/step - loss: 0.1793 - acc: 0.9237 - val_loss: 0.0400 - val_acc: 1.0000
Epoch 9/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1755 - acc: 0.9232 - val_loss: 0.0498 - val_acc: 1.0000
Epoch 10/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1751 - acc: 0.9259 - val_loss: 0.0524 - val_acc: 1.0000
Epoch 11/30
7251/7251 [==============================] - 1s 95us/step - loss: 0.1716 - acc: 0.9257 - val_loss: 0.0527 - val_acc: 1.0000
Epoch 12/30
7251/7251 [==============================] - 1s 95us/step - loss: 0.1697 - acc: 0.9261 - val_loss: 0.0571 - val_acc: 1.0000
Epoch 13/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1687 - acc: 0.9257 - val_loss: 0.0534 - val_acc: 1.0000
Epoch 14/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1653 - acc: 0.9290 - val_loss: 0.0494 - val_acc: 1.0000
Epoch 15/30
7251/7251 [==============================] - 1s 9

7251/7251 [==============================] - 2s 300us/step - loss: 0.4148 - acc: 0.8664 - val_loss: 0.3122 - val_acc: 0.7778
Epoch 2/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.2563 - acc: 0.9040 - val_loss: 0.3067 - val_acc: 0.7778
Epoch 3/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.2196 - acc: 0.9122 - val_loss: 0.2917 - val_acc: 0.9444
Epoch 4/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.2040 - acc: 0.9173 - val_loss: 0.3108 - val_acc: 0.8333
Epoch 5/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1920 - acc: 0.9218 - val_loss: 0.3185 - val_acc: 0.8333
Epoch 6/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1861 - acc: 0.9237 - val_loss: 0.3305 - val_acc: 0.7778
Epoch 7/30
7251/7251 [==============================] - 1s 96us/step - loss: 0.1840 - acc: 0.9248 - val_loss: 0.3266 - val_acc: 0.7778
Epoch 8/30
7251/7251 [==============================] - 1s 94us/s

2020-04-19 17:20:26.383660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:20:26.383704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-19 17:20:26.383709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-19 17:20:26.384001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
7251/7251 [==============================] - 2s 299us/step - loss: 0.4160 - acc: 0.8589 - val_loss: 0.3096 - val_acc: 0.8889
Epoch 2/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.2563 - acc: 0.9026 - val_loss: 0.2681 - val_acc: 0.8333
Epoch 3/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.2195 - acc: 0.9099 - val_loss: 0.2619 - val_

2020-04-19 17:20:57.481883: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 17:20:57.482282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 17:20:57.482295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 17:20:57.744625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:20:57.744656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-19 17:20:57.744663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-19 17:20:57.744955: I tensorflow/core/common_runtime/gpu/gpu_device.c

TN:  886
FP:  714
FN:  16448
TP:  9497
False Alarm Rate:  0.44625
Precision Rate:  0.9300754088727843
Recall Rate:  0.3660435536712276
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f7777ff8fd0>>
Traceback (most recent call last):
  File "/home/fpalau/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 712, in __del__
TypeError: 'NoneType' object is not callable
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 75) (7251,)
(18, 75) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 17:22:09.566489: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 17:22:09.823098: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] succ

[[  658   942]
 [15727 10218]]
              precision    recall  f1-score   support

      normal     0.0402    0.4113    0.0732      1600
      botnet     0.9156    0.3938    0.5508     25945

   micro avg     0.3948    0.3948    0.3948     27545
   macro avg     0.4779    0.4025    0.3120     27545
weighted avg     0.8647    0.3948    0.5230     27545

TN:  658
FP:  942
FN:  15727
TP:  10218
False Alarm Rate:  0.58875
Precision Rate:  0.9155913978494624
Recall Rate:  0.39383310849874736
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 75) (7251,)
(18, 75) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 17:23:22.038542: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 17:23:22.282647: I tensorflow/stream_executo

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 75, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
Total params: 138,241
Trainable params: 138,241
Non-trainable params: 0
_________________________________________________________________
None
[[  828   772]
 [ 6428 19517]]
              precision    recall  f1-score   support

      normal     0.1141    0.5175    0.1870      1600
      botnet     0.9619    0.7522    0.8443     25945

   micro avg     0.7386    0.7386    0.7386     27545
   macro avg  

2020-04-19 17:25:42.384410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:25:42.384440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-19 17:25:42.384445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-19 17:25:42.384728: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 75, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_____________________________________________________

Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 17:26:54.066876: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 17:26:54.336411: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 17:26:54.336806: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 17:26:54.336820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 17:26:54.594772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 17:26:54.594805: I tenso

7251/7251 [==============================] - 2s 279us/step - loss: 0.1615 - acc: 0.9308 - val_loss: 0.1392 - val_acc: 0.9444
Epoch 29/30
7251/7251 [==============================] - 2s 280us/step - loss: 0.1571 - acc: 0.9342 - val_loss: 0.1475 - val_acc: 0.9444
Epoch 30/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1563 - acc: 0.9335 - val_loss: 0.1396 - val_acc: 0.9444
[[ 476   76]
 [  60 1183]]
              precision    recall  f1-score   support

      normal     0.8881    0.8623    0.8750       552
      botnet     0.9396    0.9517    0.9456      1243

   micro avg     0.9242    0.9242    0.9242      1795
   macro avg     0.9138    0.9070    0.9103      1795
weighted avg     0.9238    0.9242    0.9239      1795

TN:  476
FP:  76
FN:  60
TP:  1183
False Alarm Rate:  0.13768115942028986
Precision Rate:  0.9396346306592533
Recall Rate:  0.9517296862429606
Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 17:28:06.762354: I tensorflow/core/platfo

7251/7251 [==============================] - 2s 278us/step - loss: 0.1634 - acc: 0.9295 - val_loss: 0.2343 - val_acc: 0.8889
Epoch 23/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1608 - acc: 0.9320 - val_loss: 0.4932 - val_acc: 0.8889
Epoch 24/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.1603 - acc: 0.9316 - val_loss: 0.2359 - val_acc: 0.8889
Epoch 25/30
7251/7251 [==============================] - 2s 277us/step - loss: 0.1586 - acc: 0.9316 - val_loss: 0.4151 - val_acc: 0.8889
Epoch 26/30
7251/7251 [==============================] - 2s 276us/step - loss: 0.1536 - acc: 0.9321 - val_loss: 0.4173 - val_acc: 0.8889
Epoch 27/30
7251/7251 [==============================] - 2s 277us/step - loss: 0.1551 - acc: 0.9313 - val_loss: 0.4393 - val_acc: 0.8333
Epoch 28/30
7251/7251 [==============================] - 2s 276us/step - loss: 0.1528 - acc: 0.9334 - val_loss: 0.1926 - val_acc: 0.8889
Epoch 29/30
7251/7251 [==============================

7251/7251 [==============================] - 2s 280us/step - loss: 0.1658 - acc: 0.9261 - val_loss: 0.1349 - val_acc: 0.9444
Epoch 17/30
7251/7251 [==============================] - 2s 281us/step - loss: 0.1638 - acc: 0.9269 - val_loss: 0.1332 - val_acc: 0.9444
Epoch 18/30
7251/7251 [==============================] - 2s 280us/step - loss: 0.1621 - acc: 0.9273 - val_loss: 0.1462 - val_acc: 0.8889
Epoch 19/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1588 - acc: 0.9302 - val_loss: 0.1102 - val_acc: 0.9444
Epoch 20/30
7251/7251 [==============================] - 2s 280us/step - loss: 0.1575 - acc: 0.9306 - val_loss: 0.1074 - val_acc: 0.9444
Epoch 21/30
7251/7251 [==============================] - 2s 280us/step - loss: 0.1543 - acc: 0.9298 - val_loss: 0.0985 - val_acc: 1.0000
Epoch 22/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1523 - acc: 0.9305 - val_loss: 0.0984 - val_acc: 1.0000
Epoch 23/30
7251/7251 [==============================

7251/7251 [==============================] - 2s 278us/step - loss: 0.2233 - acc: 0.9109 - val_loss: 0.0300 - val_acc: 1.0000
Epoch 4/30
7251/7251 [==============================] - 2s 278us/step - loss: 0.2091 - acc: 0.9135 - val_loss: 0.0314 - val_acc: 1.0000
Epoch 5/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.2052 - acc: 0.9166 - val_loss: 0.0229 - val_acc: 1.0000
Epoch 6/30
7251/7251 [==============================] - 2s 280us/step - loss: 0.1949 - acc: 0.9192 - val_loss: 0.0228 - val_acc: 1.0000
Epoch 7/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1956 - acc: 0.9171 - val_loss: 0.0207 - val_acc: 1.0000
Epoch 8/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1850 - acc: 0.9217 - val_loss: 0.0248 - val_acc: 1.0000
Epoch 9/30
7251/7251 [==============================] - 2s 281us/step - loss: 0.1819 - acc: 0.9225 - val_loss: 0.0225 - val_acc: 1.0000
Epoch 10/30
7251/7251 [==============================] - 2s

7251/7251 [==============================] - 4s 487us/step - loss: 0.4303 - acc: 0.8705 - val_loss: 0.6290 - val_acc: 0.8889
Epoch 2/30
7251/7251 [==============================] - 2s 280us/step - loss: 0.2631 - acc: 0.9035 - val_loss: 0.3749 - val_acc: 0.8889
Epoch 3/30
7251/7251 [==============================] - 2s 281us/step - loss: 0.2237 - acc: 0.9088 - val_loss: 0.2524 - val_acc: 0.9444
Epoch 4/30
7251/7251 [==============================] - 2s 282us/step - loss: 0.2080 - acc: 0.9112 - val_loss: 0.1998 - val_acc: 0.9444
Epoch 5/30
7251/7251 [==============================] - 2s 281us/step - loss: 0.1942 - acc: 0.9177 - val_loss: 0.2645 - val_acc: 0.8889
Epoch 6/30
7251/7251 [==============================] - 2s 280us/step - loss: 0.1920 - acc: 0.9196 - val_loss: 0.1976 - val_acc: 0.9444
Epoch 7/30
7251/7251 [==============================] - 2s 279us/step - loss: 0.1851 - acc: 0.9222 - val_loss: 0.1994 - val_acc: 0.9444
Epoch 8/30
7251/7251 [==============================] - 2s 

### Experiment LSTM different maxlen from beginning

In [ ]:
sizes_string = [10, 25]#, 75, 100, 500, 1000]
test = "ctu19_to_test.csv"
train = "ctu_13_for_LSTM.csv"
for maxlen in sizes_string:
    results = "results_LSTM_size_" + str(maxlen) + ".csv"
    for i in range(0,10):
        !python3 train_data_preparation.py --csv $train --maxlen $maxlen
        !python3 dga_classifier.py --save-model endgame.h5 --maxlen $maxlen
        !python3 train_data_preparation.py --csv $test --test-only --maxlen $maxlen
        !python3 dga_classifier.py --test-only -m endgame.h5 -r $results --maxlen $maxlen
        print("##--------------------------------------------------------------------##")

Using TensorFlow backend.
  File "dga_classifier.py", line 54
    print(test_x_data.shape, test_y_data.shape)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
Using TensorFlow backend.
  File "dga_classifier.py", line 54
    print(test_x_data.shape, test_y_data.shape)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
##--------------------------------------------------------------------##
Using TensorFlow backend.
  File "dga_classifier.py", line 54
    print(test_x_data.shape, test_y_data.shape)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
Using TensorFlow backend.
  File "dga_classifier.py", line 54
    print(test_x_data.shape, test_y_data.shape)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
##-------------------------------------------------

Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 13:52:46.898940: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:52:47.159841: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 13:52:47.160234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 13:52:47.160249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 13:52:47.419617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 13:52:47.419647: I 

[[  800   800]
 [13804 12141]]
              precision    recall  f1-score   support

      normal     0.0548    0.5000    0.0987      1600
      botnet     0.9382    0.4680    0.6244     25945

   micro avg     0.4698    0.4698    0.4698     27545
   macro avg     0.4965    0.4840    0.3616     27545
weighted avg     0.8869    0.4698    0.5939     27545

TN:  800
FP:  800
FN:  13804
TP:  12141
False Alarm Rate:  0.5
Precision Rate:  0.9381809751951163
Recall Rate:  0.46795143572942766
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 10) (7251,)
(18, 10) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 13:53:08.734790: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:53:09.000923: I tensorflow/stream_executor/cu

[[  768   832]
 [13924 12021]]
              precision    recall  f1-score   support

      normal     0.0523    0.4800    0.0943      1600
      botnet     0.9353    0.4633    0.6197     25945

   micro avg     0.4643    0.4643    0.4643     27545
   macro avg     0.4938    0.4717    0.3570     27545
weighted avg     0.8840    0.4643    0.5892     27545

TN:  768
FP:  832
FN:  13924
TP:  12021
False Alarm Rate:  0.52
Precision Rate:  0.9352680308099276
Recall Rate:  0.4633262671034881
##--------------------------------------------------------------------##
Using TensorFlow backend.
Using TensorFlow backend.
(7251, 25) (7251,)
(18, 25) (18,)
Model lstm_model_endgame selected
Training model...
(7251,)
Train on 7251 samples, validate on 18 samples
Epoch 1/30
2020-04-19 13:53:30.662829: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:53:30.923150: I tensorflow/stream_executor/cu

[[  796   804]
 [13924 12021]]
              precision    recall  f1-score   support

      normal     0.0541    0.4975    0.0975      1600
      botnet     0.9373    0.4633    0.6201     25945

   micro avg     0.4653    0.4653    0.4653     27545
   macro avg     0.4957    0.4804    0.3588     27545
weighted avg     0.8860    0.4653    0.5898     27545

TN:  796
FP:  804
FN:  13924
TP:  12021
False Alarm Rate:  0.5025
Precision Rate:  0.9373099415204679
Recall Rate:  0.4633262671034881
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fd87fd3bf28>>
Traceback (most recent call last):
  File "/home/fpalau/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 712, in __del__
  File "/home/fpalau/.local/lib/python3.5/site-packages/tensorflow/python/framework/c_api_util.py", line 31, in __init__
TypeError: 'NoneType' object is not callable
##-------------------------------------------------------------

2020-04-19 13:54:31.443963: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 13:54:31.443993: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2020-04-19 13:54:31.444016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2020-04-19 13:54:31.444315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10430 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 128)           6528      
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               131584    
_____________________________________________________

Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 13:55:03.920176: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:55:04.182958: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 13:55:04.183353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 13:55:04.183367: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 13:55:04.440985: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 13:55:04.441028: I tenso

Using TensorFlow backend.
Using TensorFlow backend.
2020-04-19 13:56:00.611097: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-19 13:56:00.887411: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-04-19 13:56:00.887809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 10.92GiB freeMemory: 10.77GiB
2020-04-19 13:56:00.887823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2020-04-19 13:56:01.151940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-19 13:56:01.151982: I tenso

7251/7251 [==============================] - 1s 93us/step - loss: 0.1576 - acc: 0.9327 - val_loss: 0.0956 - val_acc: 1.0000
Epoch 23/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1545 - acc: 0.9331 - val_loss: 0.0900 - val_acc: 1.0000
Epoch 24/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1547 - acc: 0.9335 - val_loss: 0.1023 - val_acc: 1.0000
Epoch 25/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1535 - acc: 0.9361 - val_loss: 0.0904 - val_acc: 1.0000
Epoch 26/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1503 - acc: 0.9363 - val_loss: 0.0852 - val_acc: 1.0000
Epoch 27/30
7251/7251 [==============================] - 1s 94us/step - loss: 0.1485 - acc: 0.9359 - val_loss: 0.0835 - val_acc: 1.0000
Epoch 28/30
7251/7251 [==============================] - 1s 93us/step - loss: 0.1478 - acc: 0.9364 - val_loss: 0.0910 - val_acc: 1.0000
Epoch 29/30
7251/7251 [==============================] - 1s 